# Build all images and run all containers
# `docker-compose -f docker-compose-local.yml up -d --build --force-recreate`

version: '3.7'

services:

  jstor-integration-tests:
    container_name: 'jstor-integration-tests'
    build:
      context: './'
      dockerfile: './DockerfileLocal'
    volumes:
      - './:/home/jstorforumadm'
      - '/tmp/harvested:/tmp/harvested'
      - '/tmp/transformed:/tmp/transformed'
    env_file:
      - '.env'
    environment:
      QUEUE_NAME: first_queue_itest
    ports:
      # Integration tests
      - '25003:8081'
    networks:
      - jstorforum-net

# Create a custom docker network if it does not exist already
networks:
  jstorforum-net:
    name: jstorforum-net